### PR TITLE
Don't use executor in run_http_query when return_promise=True

### LINKED ISSUE #32: broken support for AsyncioExecutor
The #13 PR introduced executors into request processing for batched queries. It also broken support for use of AsyncioExecutor from within asyncio context.

When using AsyncioExecutor this line blocks forever:

https://github.com/graphql-python/graphql-server-core/blob/427cccb00ae41fb88e8fcaf89aa64f5edb855394/graphql_server/__init__.py#L137

The `get()` method is called on Promise that must be `await`ed in async context, here it will stay `pending` forever.

Call to `wait_until_finished()` on executor does not help because `get_response` is not a coroutine and returns a Promise. Async Promises are not handled by `wait_until_finished()` method of AsyncioExecutor ([code](https://github.com/graphql-python/graphql-core/blob/a600f7c662e7a6db7d6b56e7c67bf43925b6b23d/graphql/execution/executors/asyncio.py#L47)). Even if it was, `AsyncioExecutor.wait_until_finished()` cannot run from within asyncio context and would fail for any asyncio-based application like aiohttp server.

related issue: https://github.com/graphql-python/graphql-core/issues/67

Fix to the above issue introduces a flag `return_promise` which is just what we need to handle response in async context.

implementatio details:

https://github.com/graphql-python/graphql-core/commit/b4758b1
https://github.com/graphql-python/graphql-core/commit/895b324
https://github.com/graphql-python/graphql-core/commit/cea224a

This fragment of graphql-core test show hows its intended to be used in asyncio context:

https://github.com/graphql-python/graphql-core/blob/a600f7c662e7a6db7d6b56e7c67bf43925b6b23d/tests_py35/core_execution/test_asyncio_executor.py#L65-L75

The `return_promise` lets the main application handle waiting for executors to finish its task, so graphql-server-core should respect that.

I found this issue in my aiohttp application (using [graphql-python/aiohttp-graphql](https://github.com/graphql-python/aiohttp-graphql)), all queries would block forever. I had to restrict this package version to `<=1.1.1`

### PR DESCRIPTION
**Pull request by blazewicz**
fixes #32

### CODE REVIEW

**Comment by banjoanderson** [comment]
This all looks good to me, I discovered this issue in my application as well. 

@Cito I notice you're one of the main contributors to this project after @syrusakbary opened it up to the community, are there any contributing/review guidelines we should be following?

**Comment by banjoanderson** [comment]
@Cito is there anyone else who has write access to this repository? We should really address this issue

**Comment by Cito** [comment]
@banjoanderson was swamped with work - will have a look later today.

**Comment by Cito** [comment]
Thanks a lot for working on this. I will create a 1.2 release containing this fix.

**Comment by Cito** [comment]
Version 1.2.0 has been released now.

**Pull request merged**
